<?php

/**
 * Wedding Theme Registry
 *
 * Each template maps to a theme config array used by shared components.
 * Includes: colors, fonts, Google Fonts URL, button/card styles.
 */

return [
    'tht_e_wedding_17' => [
        'primary'      => '#705746',
        'primary_dark' => '#4E392C',
        'accent'       => '#D8C5B2',
        'bg'           => '#F7F2EB',
        'card_bg'      => 'rgba(255,255,255,0.9)',
        'text'         => '#3D3028',
        'text_muted'   => '#7A6A60',
        'font_display' => "'Cormorant Garamond', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Lora', serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Great+Vibes&family=Lora:ital,wght@0,400;0,500;0,600;1,400&display=swap&subset=vietnamese',
        'radius'       => '4px',
        'btn_style'    => 'square',
        'card_style'   => 'paper',
    ],

    'tht_e_wedding_16' => [
        'primary'      => '#667856',
        'primary_dark' => '#46563B',
        'accent'       => '#A8B79B',
        'bg'           => '#F4F5EF',
        'card_bg'      => 'rgba(255,255,255,0.9)',
        'text'         => '#43503A',
        'text_muted'   => '#75806D',
        'font_display' => "'Cormorant Garamond', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Lora', serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Great+Vibes&family=Lora:ital,wght@0,400;0,500;0,600;1,400&display=swap&subset=vietnamese',
        'radius'       => '2px',
        'btn_style'    => 'square',
        'card_style'   => 'paper',
    ],

    'da05_vip' => [
        'primary'      => '#A67C52',
        'primary_dark' => '#8B6539',
        'accent'       => '#C4967A',
        'bg'           => '#FDF8F4',
        'card_bg'      => 'rgba(255,255,255,0.92)',
        'text'         => '#3D3329',
        'text_muted'   => '#6B6055',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Quicksand', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Philosopher:ital,wght@0,400;0,700;1,400;1,700&family=Great+Vibes&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=Quicksand:wght@300;400;500;600;700&display=swap',
        'radius'       => '24px',
        'btn_style'    => 'rounded',
        'card_style'   => 'glass',
    ],

    'romantic_scroll' => [
        'primary'      => '#8B4513',
        'primary_dark' => '#6B3410',
        'accent'       => '#C4967A',
        'bg'           => '#FDF5E6',
        'card_bg'      => 'rgba(255,255,255,0.95)',
        'text'         => '#4A3535',
        'text_muted'   => '#8B7070',
        'font_display' => "'Philosopher', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Quicksand', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Great+Vibes&family=Oswald:wght@400;500;600&family=Philosopher:ital,wght@0,400;0,700;1,400&family=Quicksand:wght@300;400;500;600;700&display=swap',
        'radius'       => '20px',
        'btn_style'    => 'pill',
        'card_style'   => 'solid',
    ],

    'midnight_story' => [
        'primary'      => '#C9B037',
        'primary_dark' => '#A89030',
        'accent'       => '#8B7D3C',
        'bg'           => '#0F0F1A',
        'card_bg'      => 'rgba(30,30,50,0.9)',
        'text'         => '#E8E8E8',
        'text_muted'   => '#A0A0B0',
        'font_display' => "'Cinzel', serif",
        'font_script'  => "'Playfair Display', serif",
        'font_body'    => "'Montserrat', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=Montserrat:wght@200;400;600&family=Playfair+Display:ital@0;1&display=swap&subset=vietnamese',
        'radius'       => '16px',
        'btn_style'    => 'square',
        'card_style'   => 'outline',
    ],

    'cherry_blossom' => [
        'primary'      => '#E8A0BF',
        'primary_dark' => '#D080A0',
        'accent'       => '#FFD1DC',
        'bg'           => '#FFF0F5',
        'card_bg'      => 'rgba(255,255,255,0.9)',
        'text'         => '#5D3A4A',
        'text_muted'   => '#9B7A8A',
        'font_display' => "'Dancing Script', cursive",
        'font_script'  => "'Dancing Script', cursive",
        'font_body'    => "'Nunito', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Nunito:wght@300;400;600;700&display=swap&subset=vietnamese',
        'radius'       => '28px',
        'btn_style'    => 'pill',
        'card_style'   => 'glass',
    ],

    'luxury_gold' => [
        'primary'      => '#D4AF37',
        'primary_dark' => '#B8960F',
        'accent'       => '#F5E6CC',
        'bg'           => '#1A1A2E',
        'card_bg'      => 'rgba(26,26,46,0.95)',
        'text'         => '#F0E6D3',
        'text_muted'   => '#C0B090',
        'font_display' => "'Cinzel', serif",
        'font_script'  => "'Cinzel', serif",
        'font_body'    => "'Montserrat', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600&display=swap',
        'radius'       => '12px',
        'btn_style'    => 'square',
        'card_style'   => 'outline',
    ],

    'modern_01' => [
        'primary'      => '#2D3436',
        'primary_dark' => '#1A1F20',
        'accent'       => '#6C5CE7',
        'bg'           => '#FFFFFF',
        'card_bg'      => '#F8F9FA',
        'text'         => '#2D3436',
        'text_muted'   => '#636E72',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Playfair Display', serif",
        'font_body'    => "'Be Vietnam Pro', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Be+Vietnam+Pro:wght@300;400;500&family=Pinyon+Script&display=swap',
        'radius'       => '8px',
        'btn_style'    => 'rounded',
        'card_style'   => 'shadow',
    ],

    'elegant_02' => [
        'primary'      => '#8B7355',
        'primary_dark' => '#6B5A42',
        'accent'       => '#C4A882',
        'bg'           => '#FAF6F0',
        'card_bg'      => 'rgba(255,255,255,0.88)',
        'text'         => '#4A3728',
        'text_muted'   => '#8B7B6B',
        'font_display' => "'Cormorant Garamond', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Lato', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,400&family=Great+Vibes&display=swap',
        'radius'       => '20px',
        'btn_style'    => 'pill',
        'card_style'   => 'glass',
    ],

    'galaxy_dreams' => [
        'primary'      => '#A78BFA',
        'primary_dark' => '#7C3AED',
        'accent'       => '#F0ABFC',
        'bg'           => '#0F172A',
        'card_bg'      => 'rgba(30,41,80,0.85)',
        'text'         => '#E2E8F0',
        'text_muted'   => '#94A3B8',
        'font_display' => "'Orbitron', sans-serif",
        'font_script'  => "'Exo 2', sans-serif",
        'font_body'    => "'Exo 2', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Exo+2:ital,wght@0,300;0,400;0,600;1,400&display=swap&subset=vietnamese',
        'radius'       => '16px',
        'btn_style'    => 'rounded',
        'card_style'   => 'glass',
    ],

    'minimal_03' => [
        'primary'      => '#1A1A1A',
        'primary_dark' => '#000000',
        'accent'       => '#C0C0C0',
        'bg'           => '#FFFFFF',
        'card_bg'      => '#FAFAFA',
        'text'         => '#1A1A1A',
        'text_muted'   => '#757575',
        'font_display' => "'Italiana', serif",
        'font_script'  => "'Dancing Script', cursive",
        'font_body'    => "'Jost', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Italiana&family=Jost:wght@300;400;500&family=Dancing+Script:wght@400;700&display=swap&subset=vietnamese',
        'radius'       => '4px',
        'btn_style'    => 'square',
        'card_style'   => 'solid',
    ],

    'spring_blossom' => [
        'primary'      => '#76A665',
        'primary_dark' => '#5B8A4C',
        'accent'       => '#F5C6D0',
        'bg'           => '#FDFCF7',
        'card_bg'      => 'rgba(255,255,255,0.92)',
        'text'         => '#3A4A35',
        'text_muted'   => '#7A8A70',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Playfair Display', serif",
        'font_body'    => "'Montserrat', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Montserrat:wght@300;400;500;600&display=swap',
        'radius'       => '24px',
        'btn_style'    => 'rounded',
        'card_style'   => 'glass',
    ],

    'traditional_red' => [
        'primary'      => '#C41E3A',
        'primary_dark' => '#A01830',
        'accent'       => '#D4AF37',
        'bg'           => '#FFF8F0',
        'card_bg'      => 'rgba(255,255,255,0.95)',
        'text'         => '#4A1A1A',
        'text_muted'   => '#8B5A5A',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Pinyon Script', cursive",
        'font_body'    => "'Be Vietnam Pro', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Be+Vietnam+Pro:wght@300;400;500&family=Pinyon+Script&display=swap',
        'radius'       => '16px',
        'btn_style'    => 'rounded',
        'card_style'   => 'solid',
    ],

    'vintage_gold' => [
        'primary'      => '#B8860B',
        'primary_dark' => '#8B6508',
        'accent'       => '#DAA520',
        'bg'           => '#FFFDF7',
        'card_bg'      => 'rgba(255,253,247,0.92)',
        'text'         => '#3D3422',
        'text_muted'   => '#8B8060',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Montserrat', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Great+Vibes&family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Montserrat:wght@300;400;600&display=swap',
        'radius'       => '8px',
        'btn_style'    => 'rounded',
        'card_style'   => 'solid',
    ],

    'mewedding_watercolor' => [
        'primary'      => '#7B9E89',
        'primary_dark' => '#5A7A66',
        'accent'       => '#E8C4B0',
        'bg'           => '#FAF7F2',
        'card_bg'      => 'rgba(255,255,255,0.88)',
        'text'         => '#3D4A3F',
        'text_muted'   => '#7A8B7D',
        'font_display' => "'Noto Serif', serif",
        'font_script'  => "'Dancing Script', cursive",
        'font_body'    => "'Quicksand', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Quicksand:wght@300;400;500;600;700&family=Noto+Serif:ital,wght@0,400;0,700;1,400&display=swap',
        'radius'       => '20px',
        'btn_style'    => 'pill',
        'card_style'   => 'glass',
    ],

    // Default fallback
    'default' => [
        'primary'      => '#A67C52',
        'primary_dark' => '#8B6539',
        'accent'       => '#C4967A',
        'bg'           => '#FDF8F4',
        'card_bg'      => 'rgba(255,255,255,0.92)',
        'text'         => '#3D3329',
        'text_muted'   => '#6B6055',
        'font_display' => "'Playfair Display', serif",
        'font_script'  => "'Great Vibes', cursive",
        'font_body'    => "'Quicksand', sans-serif",
        'font_url'     => 'https://fonts.googleapis.com/css2?family=Great+Vibes&family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Quicksand:wght@300;400;500;600;700&display=swap',
        'radius'       => '24px',
        'btn_style'    => 'rounded',
        'card_style'   => 'glass',
    ],
];
